### ISSUE TITLE
Bowtie2 missing in Bismark container

### ISSUE THREAD

**Issue by michalstolarczyk** [BioContainers/specs#100]
Bowtie2 software is not installed in the Bismark container: quay.io/biocontainers/bismark:0.18.1--pl5.22.0. Consquently, the `bismark_genome_preparation --bowtie2` command execution results in the following error:
```
Can't exec "bowtie2-build": No such file or directory at /usr/local/bin/bismark_genome_preparation line 178, <IN> line 75966.
Parent process: Failed to build index
```
Please see [this issue](https://github.com/databio/hub.bulker.io/issues/3) for more detail

Thank you!

**Comment by bgruening** [comment]
@michalstolarczyk not sure what happened to the 0.18.1 version. Do you need this specific one?
I think the containers are ok from everything quay.io/biocontainers/bismark:0.19.0--1 onwards ...

**Comment by michalstolarczyk** [comment]
No, I do not need this specific version. It's just the first one that pops up in the search results. Tried the latest version and it works.

Thanks!
