### ISSUE TITLE
sandbox link on specs main page broken

### ISSUE THREAD

**Issue by rsettlage** [BioContainers/specs#103]
This link (https://github.com/BioContainers/sandbox) is found here: https://github.com/BioContainers/specs

Is it just a broken link or has the workflow changed?  The issues list seems a bit stale, is this project still active?

**Comment by ypriverol** [comment]
The project is still active; the specification has not moved a lot in the last 2 years.

**Comment by ypriverol** [comment]
The link has been fixed. thanks for reporting
