### ISSUE TITLE
should we accept puppet and other orchestration programs

### ISSUE THREAD

**Issue by sauloal** [BioContainers/specs#25]
Should puppet and other orchestration programs be accepted? (http://www.quora.com/What-is-the-best-Docker-Linux-Container-orchestration-tool - http://brunorocha.org/python/dealing-with-linked-containers-dependency-in-docker-compose.html)

Some users might want to use compose (https://blog.docker.com/2015/06/compose-1-3-swarm-0-3-machine-0-3/), puppet, chef, saltstack or fig. They are program which allows the automatic definition of a set of docker containers to run, their command lines, their links and dependencies.

For example, a package (galaxy) might nee to be run in parallel and after LAMP. A user would need to first run a MySQL container and wait for it to initialize. Then run galaxy with the ports from MySQL forwarded. Then run apache for caching and static content with the folders from galaxy mapped inside.

Orchestration tools can take care of all of this complexity.

/cc @BioDocker/contributors

**Comment by ypriverol** [comment]
@sauloal Can you explain this issue?

**Comment by sauloal** [comment]
@ypriverol , sorry if I was not clear enough. I will edit the initial comment to make it clearer
