### ISSUE TITLE
Should we use shippable for testing?

### ISSUE THREAD

**Issue by sauloal** [BioContainers/specs#34]
Well,

While dockerhub gives us the errors in building, it doesn't test the programs with real data.
For that a CI would be nice and the only one that I've found really compatible with docker is 
[shippable](https://app.shippable.com/).

With shippable we can define the image to pull and create a yml file (just like all CIs) with commands to run on it.

This means we can have an automatic build from github and have shippable download a dataset and run the container on it.

Furthermore, shippable can pull the git, build the image, run the test and, it the container pass, submit the built container to dockerhub.

The disadvantage of the latter is that shippable requires the Dockerfile to be in the root of the git repository. May be in the future they change it.

What do you think? Should we advise for the usage of shippable and the creation of datasets for testing?

/cc @BioDocker/contributors

**Comment by ypriverol** [comment]
@sauloal tests should be mandatory for every docker container. I'm not sure what is the best way to implement this, but you have a big yes from my side for make tests mandatory.

**Comment by sauloal** [comment]
@ypriverol Me too. but if you run the testing inside the dockerfile, all the input temporary and output files would be inside the image. this is not acceptable.

My other idea is to have a dorckerfile for the code and another for the testing. then both would have to pass. but it is a terrible hack.

Using a service like shippable mean that it would be mandatory to create a shippable yml file for performing the testing on the container that will be shipped

**Comment by bgruening** [comment]
:+1: for advertising to use shippable. Imho for the time being a simple test like checking the output of `binary --version` is enough. Using test data and writing tests is not easy and very time-consuming. Other projects like Galaxy doing this and if we go this way at some point we should borrow a few ideas (and test data) from them :)

**Comment by sauloal** [comment]
@bgruening my argument exactly.

**Comment by ypriverol** [comment]
@sauloal @bgruening should we start with a simple `--version`  for each container.
