### ISSUE TITLE
BioDocker Paper

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/specs#62]
Hi All: 
 Bad and Good news. MCP reject our paper and I think is a good opportunity for us to try a more 
 bioinformatics journal. MCP in general is not ready for this type of paper. I'm attaching the reviewer 
 comments and some of them should be addressed for the next submission:

---

 MS ID#: MCP/2016/063172
MS TITLE: BioDocker: An open-source and community-driven framework for software standardization

Dear Dr. Perez-Riverol:

Thank you for submitting your manuscript to MCP.  It has undergone review and found to not reach the 
criteria for consideration for publication.  Consequently I must decline the above manuscript for 
publication in MCP. As noted in the attached critique, the reviewers felt that there were significant 
problems associated with the manuscript that preclude its acceptance.  

I hope you will find the enclosed comments helpful as you progress with your studies.

Thank you for considering MCP for the publication of your work. I am sorry that we could not reach a 
more favorable decision in this case but hope that this will not deter you from considering the journal in 
the future.

Sincerely,
A. Burlingame
Associate Editor

Reviewer 1
COMMENTS FOR THE AUTHOR:
General comments:
It will help to understand the rest of this review by knowing that this 
reviewer is a long-time developer of proteomics software whose familiarity 
with Docker is limited to attending a 1-day workshop on Docker and 
integration of proteogenomic tools into a Docker-driven cloud environment. 
That workshop was 1 week prior to my being asked to review this manuscript. 
Thus I can probably be expected to be more knowledgeable about Docker than 

> 90% of the target readership of this manuscript.  This manuscript describes 
> how to package in a Docker container, a proteomics application that can run 
> on a Linux operating system. That container image, built on a BioDocker base 
> image containing a Linux kernel, can then be distributed to users and 
> executed with a users data on a variety of operating systems including 
> Linux, Mac OS, or Windows. Since the majority of Proteomics software 
> currently in use represents Windows applications, the whole Docker 
> technology will foreseeably be of niche-impact until such time as Docker and 
> Microsoft work together to enable the inside of a container to hold and 
> execute a Windows kernel. Various discussion on the web seems to indicate 
> that this is underway, but without clear timelines and limitations 
> described. At the minimum this manuscript needs to more clearly describe the 
> Linux/Windows constraints and their likely evolution. Even if it did that, 
> the current niche-impact from lack of support for Windows applications 
> leaves me lukewarm toward acceptance of the manuscript. Below are some 
> specific comments for improving clarity/content of the manuscript.

Specific comments:
1.  The single most useful example that could be provided would be a 
container that could convert a Thermo .RAW file into an .mzML file. This 
would probably include Thermos freely available MSFileReader API and a 
converter such as Proteowizard.
2.  Figure 2 will be largely unintelligible to most readers and is 
currently mismatched with its legend. The legend says the central elements 
are the GitHub repositories and the BioDocker registry, but the figure has 
neither of those items explicitly indicated. This figure should be aimed at 
being comprehensible to both a proteomics software application developer and 
a software user.  Perhaps the organization is intended to have a 3rd type of 
participant, a developer whose role is limited to containerizing 
applications built by others? The term version should accompany or replace 
the term fork, otherwise users wont get it.
3.  Figure 4 is nearly useless. Just provide the URL 
http://biodocker.org, keep the dockerfile example in figure 3 and omit 
figure 4. 
4.  The supplementary note is essentially re-packaged online 
documentation that will be out-of-date soon after the publication of the 
manuscript. Consequently, I suggest omitting the supplementary note from the 
publication. The manuscript already points readers to the BioDocker website, 
which will always contain documentation that is more up-to-date.

Reviewer 2
COMMENTS FOR THE AUTHOR:
1). The paper and supplementary material seem a bit of mixture between what is
typical for a paper and
what would be more appropriate in a manual (eg Table 1, Fig. 3). For the
supplementary material I
would put links to web based manuals but include more examples.

2). I tried to install docker on my own computer to try out the example. However
the Operating
Systems required were all in advance of what I currently have. 

3). There is only a single example given of a potential use of the software. I
think the authors need to
demonstrate that the approach is going to be more generally useful than this.
For example is it
potentially applicable to packages such as MaxQuant, Skyline and MSFileReader
that run on Windows? What
percentage of the data sets in a repository such as PRIDE or MassIVE could
currently be reanalyzed with the
current components? Do you have to operate the software via command line
instructions?

The supplementary material (most of which probably isn't necessary) is
particularly bad in this regard.

5). I didn't find Fig 2 particularly useful in its current form.

6). Could the authors comment of how using this technology affects performance.
Is it appropriate to
use it for a long term installation or just for reanalysis of a data set.

7). The horizontal linesin Fig 1A don't correctly line up with the command elements.

8). In common usage software is a collective nouns. Thus you would say "a given
software
package" instead of "a given software". 

Sent on: September 21, 2016

---

**Comment by hroest** [comment]
>Since the majority of Proteomics software currently in use represents Windows applications

this seems a highly interesting comment and not one I would agree with - actually in my experience it is the opposite and most proteomics software is initially developed in a Linux environment or cross-platform. But for some readers, especially users, proteomics software may only mean "vendor software + Skyline + Maxquant", so maybe we should be more specific about how Docker opens up a whole new ecosystem of software of which some people may not even have heard before!

But in general it seems that people are worried about the ease-of-use and the fact that Windows clients are not yet fully supported. I agree with this point if we want to appeal to the common, non-technical reader and user. However for system admins, bioinformaticians etc I believe that docker is already really useful. But overall, I think the criticism boils down to the fact that we should also discuss the limitations of the technology which will lead to a more useful manuscript

**Comment by bgruening** [comment]
Paper published! https://doi.org/10.1093/bioinformatics/btx192
