### ISSUE TITLE
removing CMD examples from Dockerfile header

### ISSUE THREAD

**Issue by prvst** [BioContainers/specs#67]
I think we should remove the CMD examples from the  header metadata. Some software have complex commands, and we can't list all of them. Also, I don't think this qualifies as metadata.

**Comment by ypriverol** [comment]
I agree. Howwer we need to specify a simple command where the user can start. It can be a README page where the user can see how to run the container.

**Comment by prvst** [comment]
we can add a readme file to the repository and dockerhub pages, both can
contain examples. We can also use our wiki for that

**Comment by ypriverol** [comment]
For now less remove this from the metadata tag. Can we specify for all how to run the test for example the --version that we have been discussing in testing.

**Comment by prvst** [comment]
yes, we can add another option like ' --explain' or whatever, that will
print some examples and/or expose some of the metadata information

**Comment by ypriverol** [comment]
@prvst  with the current specification a simple page to the documentation ( #68  ) is enough. I will close this issue.
