### ISSUE TITLE
Combined searching of DIA umpire mgf files

### ISSUE THREAD

**Issue by 1Moe** [BioContainers/specs#73]
Hi there,

I have recently tried DIA-umpire to extract some pseudo MS/MS spectra from my DIA SWATH files (TripleTof 5600 wiff files) and I would like to use SearchGUI and Peptideshaker or ProteinPilot to search these mgf files. DIA umpire puts out 3 mgf files per 1 input file and the DIA umpire instructions say this:

> Each file corresponds to a different “quality level” of precursor ions (Q1= More than two isotopic peaks detected in MS1, Q2 = only two isotopic peak detected, Q3 = detected unfragmented precursor in MS2). These spectra are written to separate files, because they must be searched separately against a protein database as a consequence of differences in FDR estimates for these varying quality data.

I also found some info on the MatrixScience webpage suggesting using Q1 and Q3 together for best results http://www.matrixscience.com/blog/searching-dia-data-especially-swath.html

I'm now wondering if you could let me know the best strategy (in your opinion) to analyse the DIA umpire mgf files using searchgui and PS.

1) Do I have to search the 3 mgf files (coming from the same wiff file) separately and load together into peptideshake or can I search the 3 files together?

2) I have 50 biological samples with 3 technical replicates (3 injections per sample from the same tube). In theory I could generate 3x50x3 = 450 mgf files using DIA umpire. What would be the best combination to build a spectral library for DIA?

3) I tried searching the 3 mgf files together, comparing X!tandem and comet. Comet was the clear winner in terms of protein IDs - 9 IDs for Xtandem vs 127 IDs for Comet. Would you know the reason for this vast difference?

I have posted this here as well https://github.com/compomics/peptide-shaker/issues/243 to ask for the best strategy to search multiple mgf files.

Cheers
Moe

**Comment by prvst** [comment]
Dear @1Moe ;

BioContainers and Peptide-Shaker are not the maintainers of DIA-Umpire. Here in our case, we are only providing DIA-Umpire as a container.

If you need assistance with DIA-Umpire, I suggest you take a look at the originall [website](http://diaumpire.sourceforge.net/), as described on the publication, they have a forum there where you can speak directly to the developers/maintainers.

regards

**Comment by ypriverol** [comment]
@1Moe As @prvst suggested, we are not in charge of the software providers. Are you using the DIA-UMPIRE BioContainer?  

Probably Chih-Chiang Tsou @cctsou you can respond to this question because you are the lead developer of DIA-UMPIRE. ?

@hbarsnes or @mvaudel do you have an idea?

**Comment by ypriverol** [comment]
This issue was moved to BioContainers/containers#135
