### ISSUE TITLE
BioContainers Specifications for Training

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/specs#78]
Dear all:
 We have a meeting today about BioContainers for Training, how to generate them, How to build 
 them and best practices. The training container is not a "normal" container because it contains links 
 to data, training material, and different tagging system, it can be built with more than one software 
 inside. I have drafted the first guidelines for this type of containers to move forward them: 

1. For every Training container a new tag will be created in the LABEL called **Training**, this will allow search systems to retrieve the containers. 
```
LABEL tags "Proteomics, Training"
```
2. The data will be store in Public repositories (Public Archive) or Zenodo. 
3. The materials related to the training course should be in Zenodo, or another permanent archive.
4. The container should be able to automatically pull the deposited data into the /data folder.

5. We will work wit the Galaxy community to make available the reference data: Assemblies, UniProt releases, and other standard databases that do not make sense to deposit in Zenodo.  

Please let me know your comments. @timosachsenberg @bgruening @hbarsnes @hroest @prvst @rajido @BioContainers/contributors

**Comment by samuelpayne** [comment]
I know that Alexey is working on this too. @prvst

**Comment by ypriverol** [comment]
Yes @samuelpayne his team is involved in BioContainers.

**Comment by ypriverol** [comment]
The materials of the containers and the course should be referenced by URL for example: 

LABEL TRAINING="https://www.ebi.ac.uk/training/online/course/phenomenal-accessing-metabolomics-workflows-galaxy"

This can be an example for the training material of a galaxy instance of phonomenal2020. The Container should provide also the tag "Training" in tags to do not confuse the users.
