### ISSUE TITLE
Containers should have maintainers that can be group or consortiums

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/specs#81]
It will be really good for BioContainers Dockerfile / BioConda should contain a mechanism that annotate not only the single maintainer but also the consortium.

**Comment by ypriverol** [comment]
@bgruening  propose to improve the system by using the logs from GitHub to improve the reporting and contributors. We need to have a system that read the actual users contributors from **github**.

**Comment by prvst** [comment]
I agree with a tag for groups or consortium, but I dont think they should be 'the' responsible for the image. The responsible should, in my opinion, always be a single person who can be contacted.
