### ISSUE TITLE
More metadata into the recipes of BioConda and BioContainers

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/specs#92]
@bioconda team has proposed some major changes for the metadata extension that we should consider in the future. https://github.com/bioconda/bioconda-recipes/pull/7940

**Comment by epruesse** [comment]
W.r.t. identifiers vs URIs, as in `doi: 10.xxx/xxx` vs `https://doi.org/10.xxx/xxxx`: 

The former is officially deprecated in favor of the latter to increase visibility and ease of use. 

From https://www.crossref.org/display-guidelines/#why-not-use-doi-or-doi:

> Why not use doi: or DOI:?
> 
> When Crossref was founded in 2000 we recommended that DOIs be displayed in the format `doi:10.NNNN/doisuffix` and many members still use `doi:[space][doinumber]`, `DOI: [space][doinumber]`, or `DOI[space][doinumber]`. At the time that the DOI system was launched in the late 1990s it was thought that `doi:` would become native to browsers and automatically resolve DOIs, similar to `http:`. This never happened and it will never happen. Advantages to changing the display to a resolvable URL - even on the page the DOI itself resolves to - include the following:
> 
>   -  A DOI is both a link and an identifier. Users will more easily recognize Crossref DOIs as an actionable link, regardless of whether they know about DOIs.
>   -  Users who do not know how to right-click on the link and choose “Copy Link”, will still be able to easily copy the DOI URL.
>   -  Machines and programs (e.g. bots, etc.) will recognize the DOI as a link, thereby increasing discoverability and usage.
>
