### ISSUE TITLE
GDPR considerations for the future. 

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/specs#94]
A recent comment in the rule manuscript as pointed out the GDPR issues for the maintainer. https://github.com/ypriverol/containers-rules-manuscript/issues/51

**Comment by osallou** [comment]
Well, being in a git repo, you can't be really forgotten. Even if you are removed from maintainer etc.. label, it will still exists in git history, and it cannot be changed nor rewritten. Only "latest" update will show that you are not anymore in the maintainer field (for example).
Same for any package system, or other kind of git/svn contribution.

Furthermore, you contribute in all those cases freely to an open source project and comply with licenses etc... you give a "public" contribution/work and as such do not think it applies to GDPR.

Would be the same then asking to remove your name from a printed book, or a publication  :-(

However, if user wish to remove, at some point, his name from Dockerfile/conda recipe/... , he can ask to do so via PR
